# Generated by Django 4.2.7 on 2025-11-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='books/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='file_type',
            field=models.CharField(choices=[('PDF', 'PDF'), ('EPUB', 'EPUB'), ('VIDEO', 'VIDEO')], max_length=10),
        ),
    ]
