# Generated by Django 4.2.7 on 2025-11-26 15:46

import catalog.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cloudinary_public_id',
            field=models.CharField(blank=True, help_text='Cloudinary public_id for the file', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='file_url',
            field=models.URLField(blank=True, help_text='Direct Cloudinary URL for the file', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(blank=True, null=True, storage=catalog.storage.RawMediaCloudinaryStorage(), upload_to='books/'),
        ),
    ]
