# Generated by Django 4.2.7 on 2025-11-06 09:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='The moment the reading session began.')),
                ('ended_at', models.DateTimeField(blank=True, help_text='The moment the reading session ended (can be NULL if ongoing).', null=True)),
                ('duration_seconds', models.IntegerField(default=0, help_text='Calculated duration of the session in seconds.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_sessions', to='catalog.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reading Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadingProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for this progress record.', primary_key=True, serialize=False)),
                ('last_location', models.CharField(help_text='Page number, chapter title, or CFI (for EPUB).', max_length=255)),
                ('percent', models.FloatField(help_text='Reading completion percentage (0.0 to 100.0).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('total_time_seconds', models.IntegerField(default=0, help_text='Total accumulated reading time for this book (in seconds).')),
                ('last_opened_at', models.DateTimeField(auto_now=True, help_text='The last time the user opened this book.')),
                ('completed', models.BooleanField(default=False, help_text='True if the user has finished the book.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(help_text='The book being tracked.', on_delete=django.db.models.deletion.CASCADE, related_name='reading_progresses', to='catalog.book')),
                ('user', models.ForeignKey(help_text='The user who owns this progress record.', on_delete=django.db.models.deletion.CASCADE, related_name='reading_progresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reading Progresses',
                'ordering': ['-last_opened_at'],
                'unique_together': {('user', 'book')},
            },
        ),
    ]
