# Generated by Django 4.2.7 on 2025-12-03 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingprogress',
            name='current_page',
            field=models.IntegerField(default=0, help_text='Current page number (0-based for tracking).'),
        ),
    ]
