# Generated by Django 4.2.7 on 2025-12-04 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0004_book_cloudinary_public_id_book_file_url_and_more'),
        ('reading', '0002_readingprogress_current_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for this highlight.', primary_key=True, serialize=False)),
                ('page_number', models.IntegerField(help_text='Page number where the highlight is located.')),
                ('text_content', models.TextField(help_text='The highlighted text content.')),
                ('color', models.CharField(default='yellow', help_text='Highlight color (yellow, green, blue, pink, etc.).', max_length=20)),
                ('position_data', models.JSONField(help_text='JSON data containing position rectangles and coordinates.')),
                ('note', models.TextField(blank=True, help_text='Optional user note/annotation for this highlight.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(help_text='The book containing this highlight.', on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='catalog.book')),
                ('user', models.ForeignKey(help_text='The user who created this highlight.', on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Highlights',
                'ordering': ['page_number', 'created_at'],
                'indexes': [models.Index(fields=['user', 'book'], name='reading_hig_user_id_1dbad5_idx'), models.Index(fields=['book', 'page_number'], name='reading_hig_book_id_4b710f_idx')],
            },
        ),
    ]
