# Generated by Django 4.2.7 on 2025-12-06 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0003_highlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingsession',
            name='pages_read',
            field=models.IntegerField(default=0, help_text='Number of pages read during this session.'),
        ),
    ]
